### PR TITLE
Missing fa-500px.PNG image (+ ArrayList<ChoiceListValue> initialization optimization)

### PR DESCRIPTION
**Pull request by cedfou**
Hi @pvollenweider ,
 I added a missing PNG image ofr fa-500px

Kind regards,
Cédric

### CODE REVIEW

**Comment by cedfou** [comment]
@pvollenweider 
I checked ModuleImageChoiceListInitializerImpl and I think it's more a problem of context compatibilty between IconInitializer and ModuleImageChoiceListInitializerImpl on a site (composed via the pipe: choicelist[iconInitializer,resourceBundle,moduleImage='png'] )

I will check another change to make it works in every context/web site templates...

**Comment by cedfou** [comment]
Problem solved.

**Comment by cedfou** [comment]
I rollback the change on IconInitializer (no needed with ModuleImageCL).

I keep the add for fa-500px.png missing file (and small optimization for array initialization)

Regards

**Comment by pvollenweider** [comment]
thx!

**Comment by cedfou** [comment]
Hi Philippe and thank you for the merge!

REM: I sent you an email about this Font Awesome project because it’s a very old version in the Jahia Store (4.7) that is buggy (No preview for icon initilizer)... 
Is it possible to update the version in the Jahia Store? 
And more generally, why each new version is not released in the store??
Thx

**Comment by pvollenweider** [comment]
This commit is part of the 5.12.1 release https://github.com/Jahia/font-awesome/releases/tag/font-awesome-5.12.1

**Pull request merged**
